app = "wsg"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_KEEP_FILES = ".deploy/start.sh"

[env]
  PORT = "8080"
  SERVICE_DOMAIN = "wsg.manualpilot.com"
#  DOWNSTREAM_URL = "https://api.manualpilot.com/wsg"
  DOWNSTREAM_URL = "https://eox7ix0qarb1ynp.m.pipedream.net"

[experimental]
  auto_rollback = true
  cmd = ["/workspace/.deploy/start.sh"]

[[services]]
  internal_port = 8080
  protocol = "tcp"

[services.concurrency]
  hard_limit = 75
  soft_limit = 50
  type = "connections"

[[services.ports]]
  port = 443
