name: test
on:
  workflow_run:
    branches: [main]
    workflows: [test]
    types: [completed]


jobs:
  deploy:
    runs-on: ubuntu-latest
    container: golang

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: deploy
        run: flyctl deploy --remote-only --config ./.deploy/fly.toml
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
